
FROM prolocutor/docker-python-sqlite:3.12
#FROM 229931fb6377 #testing 
RUN cd /tmp/sqlite-autoconf-3120200 \                                                                    
        && ./configure --prefix=/usr --disable-static \                                                  
                CFLAGS="-g {{ flag -}}"         
        && make \                                                                                        
        && make install \                                                                                
        && rm -r /tmp/*                                                                                  

CMD ["python3"]

